source 'https://github.com/CocoaPods/Specs.git'

target 'ADGifLoading', :exclusive => true do
  pod "ADGifLoading", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ADGifLoading", :path => "../"

  
end
